name: CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Run repo scripts
      run: |
        tree
        printf -- "Executing \`./configure\n"
        sh ./configure
        printf -- "Executing \`./build.sh\`\n"
        sh ./build.sh
        tree
