name: build

on: [push]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

          - uses: actions/checkout@v2

          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
                java-version: 8

          - name: Configure and build using repository scripts
            run: |
                printf -- "Executing \`./configure\n"
                sh ./configure
                printf -- "Executing \`./build.sh\`\n"
                sh ./build.sh
                cd ./bin
                ls -la
